services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      # - "8000:8000" # For Edge Usage
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  default:
    external: true
    name: nginx
